import { TABLE_ALIGN } from "@/constants/ui.constants";
import { TFunction } from "i18next";

export const manageTableHeaders = (t: TFunction) => [
  {
    id: "firstName",
    align: TABLE_ALIGN.LEFT,
    numeric: false,
    disablePadding: false,
    sortable: true,
    label: t("settings.manageStudent.firstName"),
  },
  {
    id: "lastName",
    align: TABLE_ALIGN.LEFT,
    numeric: false,
    sortable: true,
    disablePadding: false,
    label: t("settings.manageStudent.lastName"),
  },
  {
    id: "class",
    align: TABLE_ALIGN.LEFT,
    numeric: false,
    disablePadding: false,
    label: t("settings.manageStudent.class"),
  },
  {
    id: "status",
    align: TABLE_ALIGN.RIGHT,
    numeric: false,
    disablePadding: false,
    label: t("settings.manageStudent.status"),
  },
];

export const mockManageTableData = [
  {
    id: 1,
    firstName: "Max",
    lastName: "Mustermann",
    class: "LF101",
    status: "imported",
  },
  {
    id: 2,
    firstName: "Erika",
    lastName: "Mustermann",
    class: "LF102",
    status: "invited",
  },
  {
    id: 3,
    firstName: "John",
    lastName: "Doe",
    class: "LF103",
    status: "onboarded",
  },
  {
    id: 4,
    firstName: "Jane",
    lastName: "Doe",
    class: "LF104",
    status: "imported",
  },
  {
    id: 5,
    firstName: "Alice",
    lastName: "Smith",
    class: "LF105",
    status: "invited",
  },
  {
    id: 6,
    firstName: "Bob",
    lastName: "Johnson",
    class: "LF106",
    status: "onboarded",
  },
  {
    id: 7,
    firstName: "Carol",
    lastName: "Lee",
    class: "LF107",
    status: "imported",
  },
  {
    id: 8,
    firstName: "David",
    lastName: "Kim",
    class: "LF108",
    status: "invited",
  },
  {
    id: 9,
    firstName: "Eva",
    lastName: "Müller",
    class: "LF109",
    status: "onboarded",
  },
  {
    id: 10,
    firstName: "Felix",
    lastName: "Schneider",
    class: "LF110",
    status: "imported",
  },
  {
    id: 11,
    firstName: "Greta",
    lastName: "Bauer",
    class: "LF111",
    status: "invited",
  },
  {
    id: 12,
    firstName: "Henrik",
    lastName: "Fischer",
    class: "LF112",
    status: "onboarded",
  },
  {
    id: 13,
    firstName: "Iris",
    lastName: "Wagner",
    class: "LF113",
    status: "imported",
  },
  {
    id: 14,
    firstName: "Jonas",
    lastName: "Weber",
    class: "LF114",
    status: "invited",
  },
  {
    id: 15,
    firstName: "Klara",
    lastName: "Hoffmann",
    class: "LF115",
    status: "onboarded",
  },
  {
    id: 16,
    firstName: "Lukas",
    lastName: "Schäfer",
    class: "LF116",
    status: "imported",
  },
  {
    id: 17,
    firstName: "Mira",
    lastName: "Keller",
    class: "LF117",
    status: "invited",
  },
  {
    id: 18,
    firstName: "Noah",
    lastName: "Zimmermann",
    class: "LF118",
    status: "onboarded",
  },
  {
    id: 19,
    firstName: "Olivia",
    lastName: "Becker",
    class: "LF119",
    status: "imported",
  },
  {
    id: 20,
    firstName: "Paul",
    lastName: "Richter",
    class: "LF120",
    status: "invited",
  },
  {
    id: 21,
    firstName: "Quinn",
    lastName: "Vogel",
    class: "LF121",
    status: "onboarded",
  },
  {
    id: 22,
    firstName: "Rosa",
    lastName: "Wolf",
    class: "LF122",
    status: "imported",
  },
  {
    id: 23,
    firstName: "Simon",
    lastName: "Krüger",
    class: "LF123",
    status: "invited",
  },
  {
    id: 24,
    firstName: "Timo",
    lastName: "Brandt",
    class: "LF124",
    status: "onboarded",
  },
  {
    id: 25,
    firstName: "Ute",
    lastName: "Frank",
    class: "LF125",
    status: "imported",
  },
  {
    id: 26,
    firstName: "Vera",
    lastName: "Hartmann",
    class: "LF126",
    status: "invited",
  },
  {
    id: 27,
    firstName: "Walter",
    lastName: "Klein",
    class: "LF127",
    status: "onboarded",
  },
  {
    id: 28,
    firstName: "Xenia",
    lastName: "Lang",
    class: "LF128",
    status: "imported",
  },
  {
    id: 29,
    firstName: "Yannick",
    lastName: "Neumann",
    class: "LF129",
    status: "invited",
  },
  {
    id: 30,
    firstName: "Zoe",
    lastName: "Otto",
    class: "LF130",
    status: "onboarded",
  },
];
