// ui
export const SET_DOCUMENT_DRAGGED_OVER = "SET_DOCUMENT_DRAGGED_OVER";
export const SET_APP_TOUCHED = "SET_APP_TOUCHED";
export const CHANGE_APPLICATION_THEME = "CHANGE_APPLICATION_THEME";
export const CHANGE_APPLICATION_LOCALE = "CHANGE_APPLICATION_LOCALE";

// Websockets:
export const APP_SOCKET_ESTABLISH_CONNECTION =
  "APP_SOCKET_ESTABLISH_CONNECTION";
export const APP_SOCKET_CLOSE_CONNECTION = "APP_SOCKET_CLOSE_CONNECTION";

// student:
export const SET_STUDENT_CURRENT_STEP = "SET_STUDENT_CURRENT_STEP";

export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const ADD_STUDENTS_REQUEST = "ADD_STUDENTS_REQUEST";
export const ADD_STUDENTS_SUCCESS = "ADD_STUDENTS_SUCCESS";
export const ADD_STUDENTS_FAILURE = "ADD_STUDENTS_FAILURE";

export const DELETE_STUDENTS_REQUEST = "DELETE_STUDENTS_REQUEST";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_FAILURE = "DELETE_STUDENTS_FAILURE";

// class:
export const GET_CLASSES_REQUEST = "GET_CLASSES_REQUEST";
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILURE = "GET_CLASSES_FAILURE";

export const ADD_CLASS_REQUEST = "ADD_CLASS_REQUEST";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE";

export const DELETE_CLASSES_REQUEST = "DELETE_CLASSES_REQUEST";
export const DELETE_CLASSES_SUCCESS = "DELETE_CLASSES_SUCCESS";
export const DELETE_CLASSES_FAILURE = "DELETE_CLASSES_FAILURE";

export const UPDATE_CLASS_REQUEST = "UPDATE_CLASS_REQUEST";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAILURE = "UPDATE_CLASS_FAILURE";

export const SET_CURRENT_CLASS = "SET_CURRENT_CLASS";
export const CLEAR_CURRENT_CLASS = "CLEAR_CURRENT_CLASS";

export const GET_CLASS_REQUEST = "GET_CLASS_REQUEST";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const GET_CLASS_FAILURE = "GET_CLASS_FAILURE";

export const GET_CLASS_STUDENTS_REQUEST = "GET_CLASS_STUDENTS_REQUEST";
export const GET_CLASS_STUDENTS_SUCCESS = "GET_CLASS_STUDENTS_SUCCESS";
export const GET_CLASS_STUDENTS_FAILURE = "GET_CLASS_STUDENTS_FAILURE";

export const ADD_STUDENTS_TO_CLASS_REQUEST = "ADD_STUDENTS_TO_CLASS_REQUEST";
export const ADD_STUDENTS_TO_CLASS_SUCCESS = "ADD_STUDENTS_TO_CLASS_SUCCESS";
export const ADD_STUDENTS_TO_CLASS_FAILURE = "ADD_STUDENTS_TO_CLASS_FAILURE";

export const REMOVE_STUDENTS_FROM_CLASS_REQUEST =
  "REMOVE_STUDENTS_FROM_CLASS_REQUEST";
export const REMOVE_STUDENTS_FROM_CLASS_SUCCESS =
  "REMOVE_STUDENTS_FROM_CLASS_SUCCESS";
export const REMOVE_STUDENTS_FROM_CLASS_FAILURE =
  "REMOVE_STUDENTS_FROM_CLASS_FAILURE";
