export interface AppAction {
  type: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  payload?: any;
  [key: string]: unknown;
}

export const SET_DOCUMENT_DRAGGED_OVER = "SET_DOCUMENT_DRAGGED_OVER";
export const SET_APP_TOUCHED = "SET_APP_TOUCHED";
export const CHANGE_APPLICATION_THEME = "CHANGE_APPLICATION_THEME";
export const CHANGE_APPLICATION_LOCALE = "CHANGE_APPLICATION_LOCALE";

export const TOGGLE_HIGH_CONTRAST = "TOGGLE_HIGH_CONTRAST";
export const TOGGLE_DYSLEXIA_FONT = "TOGGLE_DYSLEXIA_FONT";

export const APP_SOCKET_ESTABLISH_CONNECTION =
  "APP_SOCKET_ESTABLISH_CONNECTION";
export const APP_SOCKET_CLOSE_CONNECTION = "APP_SOCKET_CLOSE_CONNECTION";

export const SET_STUDENT_CURRENT_STEP = "SET_STUDENT_CURRENT_STEP";

export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const ADD_STUDENTS_REQUEST = "ADD_STUDENTS_REQUEST";
export const ADD_STUDENTS_SUCCESS = "ADD_STUDENTS_SUCCESS";
export const ADD_STUDENTS_FAILURE = "ADD_STUDENTS_FAILURE";

export const DELETE_STUDENTS_REQUEST = "DELETE_STUDENTS_REQUEST";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_FAILURE = "DELETE_STUDENTS_FAILURE";

export const VERIFY_STUDENT_REQUEST = "VERIFY_STUDENT_REQUEST";
export const VERIFY_STUDENT_SUCCESS = "VERIFY_STUDENT_SUCCESS";
export const VERIFY_STUDENT_FAILURE = "VERIFY_STUDENT_FAILURE";

export const UPDATE_STUDENT_ONBOARDING_DATA = "UPDATE_STUDENT_ONBOARDING_DATA";
export const CLEAR_STUDENT_ONBOARDING_DATA = "CLEAR_STUDENT_ONBOARDING_DATA";
export const CLEAR_STUDENT_ERROR = "CLEAR_STUDENT_ERROR";

export const LOAD_STUDENT_FOR_ONBOARDING_REQUEST =
  "LOAD_STUDENT_FOR_ONBOARDING_REQUEST";
export const LOAD_STUDENT_FOR_ONBOARDING_SUCCESS =
  "LOAD_STUDENT_FOR_ONBOARDING_SUCCESS";
export const LOAD_STUDENT_FOR_ONBOARDING_FAILURE =
  "LOAD_STUDENT_FOR_ONBOARDING_FAILURE";

export const SAVE_ONBOARDING_PROGRESS_REQUEST =
  "SAVE_ONBOARDING_PROGRESS_REQUEST";
export const SAVE_ONBOARDING_PROGRESS_SUCCESS =
  "SAVE_ONBOARDING_PROGRESS_SUCCESS";
export const SAVE_ONBOARDING_PROGRESS_FAILURE =
  "SAVE_ONBOARDING_PROGRESS_FAILURE";

export const SUBMIT_ONBOARDING_REQUEST = "SUBMIT_ONBOARDING_REQUEST";
export const SUBMIT_ONBOARDING_SUCCESS = "SUBMIT_ONBOARDING_SUCCESS";
export const SUBMIT_ONBOARDING_FAILURE = "SUBMIT_ONBOARDING_FAILURE";

export const UPDATE_STUDENT_CLASS_REQUEST = "UPDATE_STUDENT_CLASS_REQUEST";
export const UPDATE_STUDENT_CLASS_SUCCESS = "UPDATE_STUDENT_CLASS_SUCCESS";
export const UPDATE_STUDENT_CLASS_FAILURE = "UPDATE_STUDENT_CLASS_FAILURE";

// Admin student detail
export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILURE = "UPDATE_STUDENT_FAILURE";

export const CLEAR_CURRENT_STUDENT = "CLEAR_CURRENT_STUDENT";

// class:
export const GET_CLASSES_REQUEST = "GET_CLASSES_REQUEST";
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILURE = "GET_CLASSES_FAILURE";

export const ADD_CLASS_REQUEST = "ADD_CLASS_REQUEST";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE";

export const DELETE_CLASSES_REQUEST = "DELETE_CLASSES_REQUEST";
export const DELETE_CLASSES_SUCCESS = "DELETE_CLASSES_SUCCESS";
export const DELETE_CLASSES_FAILURE = "DELETE_CLASSES_FAILURE";

export const UPDATE_CLASS_REQUEST = "UPDATE_CLASS_REQUEST";
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS";
export const UPDATE_CLASS_FAILURE = "UPDATE_CLASS_FAILURE";

export const SET_CURRENT_CLASS = "SET_CURRENT_CLASS";
export const CLEAR_CURRENT_CLASS = "CLEAR_CURRENT_CLASS";

export const GET_CLASS_REQUEST = "GET_CLASS_REQUEST";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const GET_CLASS_FAILURE = "GET_CLASS_FAILURE";

export const GET_CLASS_STUDENTS_REQUEST = "GET_CLASS_STUDENTS_REQUEST";
export const GET_CLASS_STUDENTS_SUCCESS = "GET_CLASS_STUDENTS_SUCCESS";
export const GET_CLASS_STUDENTS_FAILURE = "GET_CLASS_STUDENTS_FAILURE";

export const ADD_STUDENTS_TO_CLASS_REQUEST = "ADD_STUDENTS_TO_CLASS_REQUEST";
export const ADD_STUDENTS_TO_CLASS_SUCCESS = "ADD_STUDENTS_TO_CLASS_SUCCESS";
export const ADD_STUDENTS_TO_CLASS_FAILURE = "ADD_STUDENTS_TO_CLASS_FAILURE";

export const REMOVE_STUDENTS_FROM_CLASS_REQUEST =
  "REMOVE_STUDENTS_FROM_CLASS_REQUEST";
export const REMOVE_STUDENTS_FROM_CLASS_SUCCESS =
  "REMOVE_STUDENTS_FROM_CLASS_SUCCESS";
export const REMOVE_STUDENTS_FROM_CLASS_FAILURE =
  "REMOVE_STUDENTS_FROM_CLASS_FAILURE";

export const GET_DASHBOARD_STATS_REQUEST = "GET_DASHBOARD_STATS_REQUEST";
export const GET_DASHBOARD_STATS_SUCCESS = "GET_DASHBOARD_STATS_SUCCESS";
export const GET_DASHBOARD_STATS_FAILURE = "GET_DASHBOARD_STATS_FAILURE";

export const GET_DASHBOARD_HEALTH_REQUEST = "GET_DASHBOARD_HEALTH_REQUEST";
export const GET_DASHBOARD_HEALTH_SUCCESS = "GET_DASHBOARD_HEALTH_SUCCESS";
export const GET_DASHBOARD_HEALTH_FAILURE = "GET_DASHBOARD_HEALTH_FAILURE";

export const SET_DASHBOARD_LAYOUT = "SET_DASHBOARD_LAYOUT";
export const RESET_DASHBOARD_LAYOUT = "RESET_DASHBOARD_LAYOUT";

export const GET_SETTINGS_REQUEST = "GET_SETTINGS_REQUEST";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SETTINGS_FAILURE";

export const GET_ONBOARDING_SETTINGS_REQUEST =
  "GET_ONBOARDING_SETTINGS_REQUEST";
export const GET_ONBOARDING_SETTINGS_SUCCESS =
  "GET_ONBOARDING_SETTINGS_SUCCESS";
export const GET_ONBOARDING_SETTINGS_FAILURE =
  "GET_ONBOARDING_SETTINGS_FAILURE";

export const UPDATE_SETTINGS_REQUEST = "UPDATE_SETTINGS_REQUEST";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_FAILURE = "UPDATE_SETTINGS_FAILURE";

export const UPDATE_ONBOARDING_SETTINGS_REQUEST =
  "UPDATE_ONBOARDING_SETTINGS_REQUEST";
export const UPDATE_ONBOARDING_SETTINGS_SUCCESS =
  "UPDATE_ONBOARDING_SETTINGS_SUCCESS";
export const UPDATE_ONBOARDING_SETTINGS_FAILURE =
  "UPDATE_ONBOARDING_SETTINGS_FAILURE";

export const GET_AGREEMENT_SETTINGS_REQUEST = "GET_AGREEMENT_SETTINGS_REQUEST";
export const GET_AGREEMENT_SETTINGS_SUCCESS = "GET_AGREEMENT_SETTINGS_SUCCESS";
export const GET_AGREEMENT_SETTINGS_FAILURE = "GET_AGREEMENT_SETTINGS_FAILURE";

export const UPDATE_AGREEMENT_SETTINGS_REQUEST =
  "UPDATE_AGREEMENT_SETTINGS_REQUEST";
export const UPDATE_AGREEMENT_SETTINGS_SUCCESS =
  "UPDATE_AGREEMENT_SETTINGS_SUCCESS";
export const UPDATE_AGREEMENT_SETTINGS_FAILURE =
  "UPDATE_AGREEMENT_SETTINGS_FAILURE";

export const GET_AUDIT_LOGS_REQUEST = "GET_AUDIT_LOGS_REQUEST";
export const GET_AUDIT_LOGS_SUCCESS = "GET_AUDIT_LOGS_SUCCESS";
export const GET_AUDIT_LOGS_FAILURE = "GET_AUDIT_LOGS_FAILURE";

export const GET_AUDIT_LOG_STATS_REQUEST = "GET_AUDIT_LOG_STATS_REQUEST";
export const GET_AUDIT_LOG_STATS_SUCCESS = "GET_AUDIT_LOG_STATS_SUCCESS";
export const GET_AUDIT_LOG_STATS_FAILURE = "GET_AUDIT_LOG_STATS_FAILURE";

export const EXPORT_AUDIT_LOGS_REQUEST = "EXPORT_AUDIT_LOGS_REQUEST";
export const EXPORT_AUDIT_LOGS_SUCCESS = "EXPORT_AUDIT_LOGS_SUCCESS";
export const EXPORT_AUDIT_LOGS_FAILURE = "EXPORT_AUDIT_LOGS_FAILURE";

export const CLEAR_AUDIT_LOGS_REQUEST = "CLEAR_AUDIT_LOGS_REQUEST";
export const CLEAR_AUDIT_LOGS_SUCCESS = "CLEAR_AUDIT_LOGS_SUCCESS";
export const CLEAR_AUDIT_LOGS_FAILURE = "CLEAR_AUDIT_LOGS_FAILURE";

export const SET_AUDIT_LOG_FILTERS = "SET_AUDIT_LOG_FILTERS";
export const SET_AUDIT_LOG_PAGE = "SET_AUDIT_LOG_PAGE";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE";

export const AUTH_SETUP_REQUEST = "AUTH_SETUP_REQUEST";
export const AUTH_SETUP_SUCCESS = "AUTH_SETUP_SUCCESS";
export const AUTH_SETUP_FAILURE = "AUTH_SETUP_FAILURE";

export const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

export const AUTH_CHECK_SESSION_REQUEST = "AUTH_CHECK_SESSION_REQUEST";
export const AUTH_CHECK_SESSION_SUCCESS = "AUTH_CHECK_SESSION_SUCCESS";
export const AUTH_CHECK_SESSION_FAILURE = "AUTH_CHECK_SESSION_FAILURE";

export const AUTH_CHECK_SETUP_REQUEST = "AUTH_CHECK_SETUP_REQUEST";
export const AUTH_CHECK_SETUP_SUCCESS = "AUTH_CHECK_SETUP_SUCCESS";
export const AUTH_CHECK_SETUP_FAILURE = "AUTH_CHECK_SETUP_FAILURE";

export const AUTH_SYNC_SESSION = "AUTH_SYNC_SESSION";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";

export const AUTH_UPDATE_SETUP_WIZARD = "AUTH_UPDATE_SETUP_WIZARD";
export const AUTH_CLEAR_SETUP_WIZARD = "AUTH_CLEAR_SETUP_WIZARD";

export const AUTH_UPDATE_PROFILE_REQUEST = "AUTH_UPDATE_PROFILE_REQUEST";
export const AUTH_UPDATE_PROFILE_SUCCESS = "AUTH_UPDATE_PROFILE_SUCCESS";
export const AUTH_UPDATE_PROFILE_FAILURE = "AUTH_UPDATE_PROFILE_FAILURE";

export const AUTH_FETCH_PROFILE_REQUEST = "AUTH_FETCH_PROFILE_REQUEST";
export const AUTH_FETCH_PROFILE_SUCCESS = "AUTH_FETCH_PROFILE_SUCCESS";
export const AUTH_FETCH_PROFILE_FAILURE = "AUTH_FETCH_PROFILE_FAILURE";
