// ui
export const SET_DOCUMENT_DRAGGED_OVER = "SET_DOCUMENT_DRAGGED_OVER";
export const SET_APP_TOUCHED = "SET_APP_TOUCHED";
export const CHANGE_APPLICATION_THEME = "CHANGE_APPLICATION_THEME";
export const CHANGE_APPLICATION_LOCALE = "CHANGE_APPLICATION_LOCALE";

// Websockets:
export const APP_SOCKET_ESTABLISH_CONNECTION =
  "APP_SOCKET_ESTABLISH_CONNECTION";
export const APP_SOCKET_CLOSE_CONNECTION = "APP_SOCKET_CLOSE_CONNECTION";

// student:
export const SET_STUDENT_CURRENT_STEP = "SET_STUDENT_CURRENT_STEP";

export const GET_STUDENTS_REQUEST = "GET_STUDENTS_REQUEST";
export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const GET_STUDENTS_FAILURE = "GET_STUDENTS_FAILURE";

export const ADD_STUDENTS_REQUEST = "ADD_STUDENTS_REQUEST";
export const ADD_STUDENTS_SUCCESS = "ADD_STUDENTS_SUCCESS";
export const ADD_STUDENTS_FAILURE = "ADD_STUDENTS_FAILURE";

export const DELETE_STUDENTS_REQUEST = "DELETE_STUDENTS_REQUEST";
export const DELETE_STUDENTS_SUCCESS = "DELETE_STUDENTS_SUCCESS";
export const DELETE_STUDENTS_FAILURE = "DELETE_STUDENTS_FAILURE";
