// ui
export const SET_DOCUMENT_DRAGGED_OVER = "SET_DOCUMENT_DRAGGED_OVER";
export const SET_APP_TOUCHED = "SET_APP_TOUCHED";
export const CHANGE_APPLICATION_THEME = "CHANGE_APPLICATION_THEME";
export const CHANGE_APPLICATION_LOCALE = "CHANGE_APPLICATION_LOCALE";

// Websockets:
export const APP_SOCKET_ESTABLISH_CONNECTION =
  "APP_SOCKET_ESTABLISH_CONNECTION";
export const APP_SOCKET_CLOSE_CONNECTION = "APP_SOCKET_CLOSE_CONNECTION";
